apiVersion: v1
kind: Service
metadata:
  labels:
    app: ai-deploy
  name: test
spec:
  ports:
  - port: 8501
    nodePort: 30220
    protocol: TCP
    targetPort: 8501
  selector:
    app: ai-deploy
  type: NodePort
